"""Domain types for the constructed reference set: candidates and the two case shapes.

No public dataset covers Spanish tenancy law under this taxonomy, so the reference
set is generated by construction and filtered by a human reviewer. A generated case
is a :class:`Candidate`: a Mode 1 or Mode 2 reference case, its :class:`Provenance`,
and a :class:`ReviewStatus`. Only an accepted candidate is materialized into the
versioned set the harness consumes; the label is correct by construction and the
human accepts, rejects or edits rather than authors.
"""

from datetime import date, datetime
from enum import StrEnum

from pydantic import BaseModel, model_validator

from lexme.mode1.models import Outcome
from lexme.mode2.risk import RiskLevel

CLAUSE_LEVELS: frozenset[RiskLevel] = frozenset(
    {RiskLevel.ILEGAL, RiskLevel.PEOR_QUE_DEFAULT, RiskLevel.NEGOCIABLE, RiskLevel.CORRECTO}
)


class CaseKind(StrEnum):
    """Which harness suite a candidate targets."""

    MODE1 = "modo1"
    MODE2 = "modo2"


class ReviewStatus(StrEnum):
    """A candidate's position in the human review filter.

    ``PENDING`` has not been reviewed and must never reach the set; ``ACCEPTED``
    passed the filter and is materialized; ``REJECTED`` was filtered out with a
    reason recorded.
    """

    PENDING = "pendiente"
    ACCEPTED = "aceptado"
    REJECTED = "rechazado"


class Provenance(BaseModel):
    """Where a case came from, so an accepted set carries its own audit trail.

    ``generator`` names the process that built it; ``sources`` are the corpus
    block ids or clause-bank ids it was constructed from; ``model`` is the pinned
    LLM identity when a model was involved, or ``None`` for a purely code-assembled
    case. The ``reviewed_*`` fields are stamped only when the case is accepted or
    rejected, so an unreviewed case cannot masquerade as reviewed.
    """

    generator: str
    sources: list[str] = []
    model: str | None = None
    generated_at: datetime
    reviewed_by: str | None = None
    reviewed_at: datetime | None = None
    review_note: str = ""


class KeyPoint(BaseModel):
    """One legal claim a good Mode 1 answer must contain, anchored to its block.

    ``claim`` is extracted from the block's own text, so the reference the judge
    checks against is correct by construction; ``block_ref`` must be one of the
    case's gold blocks.
    """

    claim: str
    block_ref: str


class ClarificationAnswer(BaseModel):
    """The reply the case brings for one critical branch the run may pause on.

    Unlike the question and the key points, this is not extracted from the corpus:
    it is a fact about the tenant's own case, so it is written by the reviewer and
    travels with the case as reviewed data rather than as a runtime guess.
    """

    branch_id: str
    answer: str


class Mode1ReferenceCase(BaseModel):
    """A Mode 1 case with the reference a with-reference judge checks against.

    ``gold_block_refs`` are the norm-qualified blocks a correct answer must
    ground on, fixed by construction from the seed. ``expected_outcome`` is the outcome the case was
    built to reach. ``key_points`` are the claims a good answer must contain, each
    tied to a gold block. ``target_date`` pins the point-in-time clock when the
    case is time-sensitive, and is ``None`` otherwise. ``clarification_answers``
    are the replies the case brings for the critical branches, at most one per
    branch. The serialized form is a superset of the harness's own case shape, so
    an accepted case is consumed directly by ``eval``.
    """

    id: str
    question: str
    gold_block_refs: list[str] = []
    expected_outcome: Outcome
    key_points: list[KeyPoint] = []
    target_date: date | None = None
    clarification_answers: list[ClarificationAnswer] = []

    @model_validator(mode="after")
    def _one_answer_per_branch(self) -> "Mode1ReferenceCase":
        """Reject a branch answered twice, which would make the reply ambiguous."""
        branch_ids = [pinned.branch_id for pinned in self.clarification_answers]
        if len(branch_ids) != len(set(branch_ids)):
            raise ValueError(f"two clarification answers pinned for the same branch: {branch_ids}")
        return self

    @model_validator(mode="after")
    def _key_points_cite_gold_blocks(self) -> "Mode1ReferenceCase":
        """Reject a key point whose block is not among the case's gold blocks."""
        gold = set(self.gold_block_refs)
        for point in self.key_points:
            if point.block_ref not in gold:
                raise ValueError(
                    f"key point cites block '{point.block_ref}' absent from "
                    f"gold blocks {sorted(gold)}"
                )
        return self


class ClauseGroundTruth(BaseModel):
    """One assembled clause with its known level and its known character span.

    ``start`` and ``end`` are the half-open character range of the clause body in
    the assembled document, so the segmentation layer's reference boundaries come
    for free. ``expected_level`` is the clause's constructed label, one of the four
    clause levels (never ``AUSENTE``). ``chk_ids`` records which checklist items the
    clause reflects, and is empty for a negotiable clause off the checklist.
    """

    clause_id: str
    heading: str
    text: str
    start: int
    end: int
    expected_level: RiskLevel
    chk_ids: list[str] = []
    source: str

    @model_validator(mode="after")
    def _level_is_a_clause_level(self) -> "ClauseGroundTruth":
        """Reject ``AUSENTE``, which grades an absence and never labels a clause."""
        if self.expected_level not in CLAUSE_LEVELS:
            raise ValueError(
                f"clause level must be one of {sorted(level.value for level in CLAUSE_LEVELS)}, "
                f"got '{self.expected_level.value}'"
            )
        return self


class ExpectedAbsence(BaseModel):
    """A checklist protection the assembled contract deliberately omits (a white).

    ``item_id`` is the omitted checklist item and ``right`` its plain-language
    protection; the expected level is always ``AUSENTE`` by definition.
    """

    item_id: str
    right: str
    level: RiskLevel = RiskLevel.AUSENTE


class Mode2ReferenceCase(BaseModel):
    """A synthetic contract with per-clause ground truth and its expected whites.

    ``document`` is the assembled contract text the clause spans index into;
    ``clauses`` carry the per-clause level and boundaries; ``expected_absences``
    are the checklist items no clause covers, the ⚪ the cross-check must surface.
    """

    id: str
    document: str
    clauses: list[ClauseGroundTruth] = []
    expected_absences: list[ExpectedAbsence] = []


class Candidate(BaseModel):
    """A generated case awaiting, or having passed, the human review filter.

    Exactly one of ``mode1`` / ``mode2`` is set, per ``kind``. ``provenance``
    travels with the case for the whole lifecycle. ``id`` mirrors the payload's id
    so the store can address a candidate without unpacking its kind.
    """

    kind: CaseKind
    status: ReviewStatus = ReviewStatus.PENDING
    provenance: Provenance
    mode1: Mode1ReferenceCase | None = None
    mode2: Mode2ReferenceCase | None = None

    @model_validator(mode="after")
    def _payload_matches_kind(self) -> "Candidate":
        """Reject a candidate whose payload does not match its declared kind."""
        if self.kind is CaseKind.MODE1 and (self.mode1 is None or self.mode2 is not None):
            raise ValueError("a modo1 candidate must set 'mode1' and only 'mode1'")
        if self.kind is CaseKind.MODE2 and (self.mode2 is None or self.mode1 is not None):
            raise ValueError("a modo2 candidate must set 'mode2' and only 'mode2'")
        return self

    @property
    def id(self) -> str:
        """The candidate's id, taken from whichever payload it carries."""
        payload = self.mode1 or self.mode2
        assert payload is not None  # guaranteed by _payload_matches_kind
        return payload.id
